version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  postgres:
    container_name: postgres-container
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - POSTGRES_HOST_AUTH=trust

  app:
    container_name: app-container
    build:
      context: .
      dockerfile: ./Dockerfile
      target: base
    ports:
      - '8080:8080'
    environment:
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - MONGODB_URI=${MONGODB_URI}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - mongo
      - postgres
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; go run cmd/app/main.go"
